
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - 4000:4000
    depends_on:
      - product-service
      - order-service
      - auth-service
      - review-service
      - user-service
      - cart-service
      - payment-service
  product-service:
    build: ./services/product-service
    volumes:
      - ./services/product-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
  order-service:
    build: ./services/order-service
    volumes:
      - ./services/order-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
  auth-service:
    build: ./services/auth-service
    volumes:
      - ./services/auth-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
  review-service:
    build: ./services/review-service
    volumes:
      - ./services/review-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
  admin-dashboard:
    build: ./admin-dashboard
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=http://api-gateway:4000/api
    depends_on:
      - api-gateway

  ecommerce-frontend:
    build: ./ecommerce-frontend
    ports:
      - 3001:80
    environment:
      - REACT_APP_API_URL=http://api-gateway:4000/api
    depends_on:
      - api-gateway

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - admin-dashboard
  user-service:
    build: ./services/user-service
    volumes:
      - ./services/user-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
  cart-service:
    build: ./services/cart-service
    volumes:
      - ./services/cart-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/data
  payment-service:
    build: ./services/payment-service
    volumes:
      - ./services/payment-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

volumes:
  mongo-data: null
