services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - product-service
      - order-service
      - auth-service

  product-service:
    build: ./services/product-service
    volumes:
      - ./services/product-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  order-service:
    build: ./services/order-service
    volumes:
      - ./services/order-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  auth-service:
    build: ./services/auth-service
    volumes:
      - ./services/auth-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway

volumes:
  mongo-data:
